version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
  # mongo:
  #   image: mongo
  #   volumes:
  #     - mongo-data:/data/db
  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MONGODB_URI=mongodb://mongo:27017/test
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
volumes:
  mongo-data: 
    driver: local
  jenkins_home:
    driver: local